### ISSUE TITLE
Hi i just accessed the app via web and sent some CRO by mistake

### ISSUE THREAD

**Issue by sdafactory** [giansalex/cassini-dapp#1]
Hi there...

I was seaching for new proyects on cronos network and i saw a post of  CromUK wich has done a table with all new proyects.
Wich i found interesting https://airtable.com/shrFtMD61leDezvRM/tblBHDX8RBNUOP5BG/viw4orrWrbgNkL1Z4/rec5oZuwCAG2JvdYP

Well i saw yours https://giansalex.github.io/cassini-dapp/  and i sent 9 CRO by mistake thinking it was already working... would you be so kind to send them back?

https://cronos.crypto.org/explorer/tx/0xd29a8832634955b1239f2b832d79c1ff414dda987d7dd5ab79ec88663bbcc50a/internal-transactions

Open your twitter private message posbility so i dont need to reopen my git account to send here a message :D hehe

**Comment by giansalex** [comment]
Sorry, this was deployed for testnet

**Comment by sdafactory** [comment]
So nothing i can do now??
________________________________
